import './globals.css'
import ServerStatus from '@/components/ServerStatus'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ 
  children
 }: {
  children: React.ReactNode
}){
  return (
    <html lang="en">
      <body>
          <div className="flex flex-col min-h-screen">
          <main className="flex-grow">
            {children}
          </main>
          <ServerStatus
            totalServers={11}
            serversUp={10}
            serversDown={1}
            serversPaused={0}
          />
          </div>
      </body>
    </html>
  );
}